from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.textbox = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.textbox.setFont(font)
        self.textbox.setObjectName("textbox")
        self.button_new = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.button_new.setFont(font)
        self.button_new.setObjectName("button_new")
        self.button_cam = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.button_cam.setFont(font)
        self.button_cam.setObjectName("button_cam")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.splitter_2.setFont(font)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.button_train_new = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.button_train_new.setFont(font)
        self.button_train_new.setObjectName("button_train_new")
        self.button_train_more = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.button_train_more.setFont(font)
        self.button_train_more.setObjectName("button_train_more")
        self.verticalLayout.addWidget(self.splitter_2)
        self.frame_open_cv = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_open_cv.setFont(font)
        self.frame_open_cv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_open_cv.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_open_cv.setLineWidth(1)
        self.frame_open_cv.setObjectName("frame_open_cv")
        self.verticalLayout.addWidget(self.frame_open_cv)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox_gesturelist = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_gesturelist.setFont(font)
        self.groupBox_gesturelist.setObjectName("groupBox_gesturelist")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_gesturelist)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_gesturelist = QtWidgets.QScrollArea(self.groupBox_gesturelist)
        self.scrollArea_gesturelist.setWidgetResizable(True)
        self.scrollArea_gesturelist.setObjectName("scrollArea_gesturelist")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 151, 483))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gesture1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.gesture1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesture1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gesture1.setObjectName("gesture1")
        self.verticalLayout_2.addWidget(self.gesture1)
        self.gesture2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.gesture2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesture2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gesture2.setObjectName("gesture2")
        self.verticalLayout_2.addWidget(self.gesture2)
        self.gesture3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.gesture3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesture3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gesture3.setObjectName("gesture3")
        self.verticalLayout_2.addWidget(self.gesture3)
        self.gesture4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.gesture4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesture4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gesture4.setObjectName("gesture4")
        self.verticalLayout_2.addWidget(self.gesture4)
        self.gesture5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.gesture5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesture5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gesture5.setObjectName("gesture5")
        self.verticalLayout_2.addWidget(self.gesture5)
        self.gesture6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.gesture6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gesture6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gesture6.setObjectName("gesture6")
        self.verticalLayout_2.addWidget(self.gesture6)
        self.scrollArea_gesturelist.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea_gesturelist, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_gesturelist)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_new.setText(_translate("MainWindow", "New"))
        self.button_cam.setText(_translate("MainWindow", "Cam"))
        self.button_train_new.setText(_translate("MainWindow", "Train New"))
        self.button_train_more.setText(_translate("MainWindow", "Train More"))
        self.groupBox_gesturelist.setTitle(_translate("MainWindow", "List of Gestures"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

